//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdFunding_nastya.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrowdfundingnastyaEntities : DbContext
    {
        public CrowdfundingnastyaEntities()
            : base("name=CrowdfundingnastyaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblBlog> tblBlogs { get; set; }
        public virtual DbSet<tblBlogAttachedFile> tblBlogAttachedFiles { get; set; }
        public virtual DbSet<tblBlogCategory> tblBlogCategories { get; set; }
        public virtual DbSet<tblBlogPriority> tblBlogPriorities { get; set; }
        public virtual DbSet<tblBlogType> tblBlogTypes { get; set; }
        public virtual DbSet<tblCareer> tblCareers { get; set; }
    }
}
