//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdFunding_nastya.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblBlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBlog()
        {
            this.tblBlogAttachedFiles = new HashSet<tblBlogAttachedFile>();
        }
    
        public int BlogId { get; set; }
        public string BlogTitle { get; set; }
        public string ThumbnailImage { get; set; }
        public string BlogDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> BlogTypeId { get; set; }
        public Nullable<int> AttachedFileId { get; set; }
        [NotMapped]
        public HttpPostedFileBase BlogThumbnailImage { get; set; }
        [NotMapped]
        public List<HttpPostedFileBase> BlogAttachedFiles { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBlogAttachedFile> tblBlogAttachedFiles { get; set; }
        public virtual tblBlogAttachedFile tblBlogAttachedFile { get; set; }
        public virtual tblBlogCategory tblBlogCategory { get; set; }
        public virtual tblBlogPriority tblBlogPriority { get; set; }
        public virtual tblBlogType tblBlogType { get; set; }
    }
}
