//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdFunding_nastya.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class tblCareer
    {
        public int CareerId { get; set; }
        public string CareerTitle { get; set; }
        public string CareerThumbnailImage { get; set; }
        [AllowHtml]
        public string CareerDescription { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime PublishDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> BlogTypeId { get; set; }
    
        public virtual tblPriority tblPriority { get; set; }
        public virtual tblType tblType { get; set; }
        public virtual tblCategory tblCategory { get; set; }
    }
}
