//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdFunding_nastya.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class tblEditPage
    {
        public int ID { get; set; }
        [AllowHtml]
        public string About { get; set; }
        [AllowHtml]
        public string TermsCondition { get; set; }
        [AllowHtml]
        public string Contact { get; set; }
        [AllowHtml]
        public string Privacy { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        [AllowHtml]
        public string Address { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Google { get; set; }
        public string Linkdin { get; set; }
        public string Twitter { get; set; }
    }
}
