//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdFunding_nastya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetting
    {
        public int SettingId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Port { get; set; }
        public string SMTP { get; set; }
        public Nullable<bool> IsAdminReceived { get; set; }
        public string AdminEmail { get; set; }
        public string clientId { get; set; }
        public string clientSecret { get; set; }
        public string AccountType { get; set; }
        public Nullable<double> AdditionalCost { get; set; }
        public string Feetype { get; set; }
        public Nullable<double> FeeAmount { get; set; }
        public Nullable<int> Editby { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
