//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdFunding_nastya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWithdraw
    {
        public int WithdrawId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AccountTitle { get; set; }
        public string BankName { get; set; }
        public string AccountDetail { get; set; }
        public string ImagePath { get; set; }
        public string TransactionNo { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual tblWithdrawStatu tblWithdrawStatu { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
